### ISSUE TITLE
Full text in rss feed

### ISSUE THREAD

**Issue by waldyrious** [pypy/pypy.org#11]
The feed for the old blog showed the full text of the posts in feed readers. The new blog feed only shows a snippet. It would be nice to preserve the same experience and avoid the extra click / page load.

**Comment by mattip** [comment]
Fixed this in #10 yesterday. You may need to reload the feed in order to get the full post from this week, but certainly going forward new posts will have the full text.

**Comment by waldyrious** [comment]
Oh. Interesting — I use Feedly, which only shows recent entries (newer than 30 days) as unread, so I only saw the "PyPy's blog has moved" post, which appeared in teaser mode; however, explicitly asking Feedly to show the older entries, I can see that _their_ text is fully shown in the feed. Probably just a weird glitch. Thanks for the quick update!
