### ISSUE TITLE
File Issue

### ISSUE THREAD

**Issue by Yash-Varshney-Creativities** [pypy/pypy.org#12]
Hi, Can you tell guys where is the homepage HTML file?
I wanted to contribute.

<em><b>Thanks</b></em>
[Yash](https://yash-varshney.herokuapp.com/)

**Comment by mattip** [comment]
Welcome. What in particular did you want to work on?

The homepage HTML file is generated. The basic content is in `pages/index.rst`. The `./README.md` describes the process used to turn that into `index.html` via [Nikola](https://getnikola.com/). The content is munged by Nikola via our templates, which are in `themes/pypy/templates`, and styled by the CSS in `themes/pypy/assets/css`. The top navbar menu uses javascript scripts from `themes/pypy/assets/js`.

**Comment by Yash-Varshney-Creativities** [comment]
Thanks
