### ISSUE TITLE
Hosting on GitHub Pages?

### ISSUE THREAD

**Issue by ewdurbin** [pypy/pypy.org#120]
I am currently running through an audit of everything we're hosting on the PSF infrastructure (specifically to prepare for a major distro upgrade of our older fleet of servers).

I noticed that the hosting we're doing for www.pypy.org is fairly rudimentary, effectively just cloning the [gh-pages](https://github.com/pypy/pypy.org/tree/gh-pages) branch and foisting that up behind an nginx server with a TLS certificate.

GitHub Pages is likely a much stronger fit for this since PyPy is now hosted on GH. That would provide you with a CDN and less delay in getting updates published.

Could the PyPy team consider making this migration?

**Comment by ewdurbin** [comment]
cc @mattip

**Comment by mattip** [comment]
Makes sense. I think the path forward is to carefully follow https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages, and to set the custom domain part of https://github.com/pypy/pypy.org/settings/pages. Do we need to add a CNAME file to the root of the repo? @fijal is this something you have experience with (as the owner of the DNS)?

**Comment by mattip** [comment]
The pages are already live at https://pypy.github.io/pypy.org/

**Comment by fijal** [comment]
I definitely don't have experience with that. I can sort it out if that's what you want though

**Comment by ewdurbin** [comment]
I think that's the preference for me, as it is easier ultimately... and provides a better experience for users and maintainers.

It indeed should just be a matter configuring CNAME in GitHub pages and updating DNS.

**Comment by mattip** [comment]
@fijal you should have all the permissions needed since you are an owner here. Let me know if there is anything I can do.

**Comment by ewdurbin** [comment]
Checking in on this. We're proceeding with our updates and want to make a plan for if we need to include the VM we are hosing for pypy-www currently.

**Comment by fijal** [comment]
I won't have time to read any documentation in the next few weeks. I
can easily move pypy (which is static html right?) to baroquesoftware
if PSF is unhappy

**Comment by ewdurbin** [comment]
This isn't a matter of unhappiness, just practicality. If it's something that you will have time for at some point and can commit to it, we'll hold off on migrating the current backend hosts, which will necessitate similar DNS updates.

**Comment by mattip** [comment]
@fijal I have configured this repo to use pypy.org for the gh-pages branch. If you could (as documented [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain) 
- create a CNAME domain record pointing www.pypy.org to pypy.github.io
- create A records pointing to the github IPs
```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```
- and/or create AAAA records pointing to the github IPs
```
2606:50c0:8000::153
2606:50c0:8001::153
2606:50c0:8002::153
2606:50c0:8003::153
```

Please let me know when you do this so I can verify the change.

**Comment by mattip** [comment]
We moved the hosting off PSF infrastructure. Thanks @ewdurbin.

**Comment by ewdurbin** [comment]
thanks all!

**Comment by cfbolz** [comment]
thank you @fijal and @mattip, and thank you @ewdurbin!
