### ISSUE TITLE
Remove conda-forge mentions in download page

### ISSUE THREAD

**Issue by ZeroAurora** [pypy/pypy.org#139]
Now as [conda-forge sunsetting PyPy](https://pypy.org/posts/2024/08/conda-forge-proposes-dropping-support-for-pypy.html), should we remove following statements from the download page:

> There are also pre-compiled binaries available on [conda-forge](https://pypy.org/posts/2022/11/pypy-and-conda-forge.html). We have found conda-forge a convenient and cooperative community for distributing not only the interpreter, but many packages like SciPy that are difficult to build and which do not yet have binary PyPy builds available on PyPI.

I want to remind this because I noticed this statement and was raised interest. However when I tried to install PyPy from conda-forge I only get a 3.9 version. I think others would behave like me too.

**Comment by mattip** [comment]
Sure. Want to submit a PR to remove that sentence?

**Comment by ZeroAurora** [comment]
OK will do
