### ISSUE TITLE
pypy.org website is down.

### ISSUE THREAD

**Issue by Mariatta** [pypy/pypy.org#23]
**Describe the problem**
www.pypy.org is down, currently. April 29, 2021 8:52 PM PST

**To Reproduce**
Go to www.pypy.org

**Expected behavior**
It returns 200 OK status

**Screenshots**
![Screen Shot 2021-04-28 at 8 51 44 PM](https://user-images.githubusercontent.com/5844587/116500518-8f0aa400-a863-11eb-96d1-d6221fd39eca.png)

**Comment by hugovk** [comment]
Working for me, maybe it was a temporary issue?

![image](https://user-images.githubusercontent.com/1324225/116527623-91acde00-a8e3-11eb-9bda-1183aa3ce619.png)

**Comment by Mariatta** [comment]
Works for me now too!
