### ISSUE TITLE
Can't write comments on blog post

### ISSUE THREAD

**Issue by reubano** [pypy/pypy.org#47]
**Describe the problem**
JS comment plugin doesn't appear to load

**To Reproduce**
1. Go to [mac-meets-arm64](https://www.pypy.org/posts/2020/12/mac-meets-arm64-940822335619099039.html#utterances-thread)
2. Click on 'Comments'
3. Nothing happens

**Expected behavior**

A box to open so I can write a comment

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1
 - Browser: chrome v96.0.4664.110, safari v15.1, and FF v95.0

**Additional context**

**Comment by mattip** [comment]
Weird. It seems the snippet to inject the uterance.io JavaScript is only getting emitted on the latest post, all others are missing the integration.

**Comment by mattip** [comment]
Ahh, I see. The original blog post was migrated to here from the [old blogger site](https://morepypy.blogspot.com/2020/12/mac-meets-arm64.html). Comments on the older posts are not enabled. 

Did you have a question or comment around the post? Perhaps ask on `#pypy` or on the [pypy-dev mailing list](https://mail.python.org/mailman/listinfo/pypy-dev)

**Comment by mattip** [comment]
That post did get an update [announcing the M1 support](https://www.pypy.org/posts/2022/07/m1-support-for-pypy.html) which will be part of the next release. I will close this, please feel free to reach out.
