### ISSUE TITLE
opencollective paypal payments not working

### ISSUE THREAD

**Issue by reubano** [pypy/pypy.org#48]
**Describe the problem**
A clear and concise description of what the bug is: what pages it affects and how to see it

**To Reproduce**
1. Go to [supporter page](https://opencollective.com/pypy/contribute/supporter-6604/checkout/payment)
2. Click on 'Pay w Paypal'

<img width="820" alt="Screen Shot 2021-12-22 at 12 50 10" src="https://user-images.githubusercontent.com/157864/147141049-5a246a37-cbf6-4977-8b16-7b207c935bb0.png">

**Expected behavior**
 
No error

**Desktop (please complete the following information):**
- OS: macOS 12.0.1 
- Browser: FF v95.0

**Comment by mattip** [comment]
It seems to have been a temporary failure. Please try again.

**Comment by mattip** [comment]
Closing, please reopen if it returns.
