### ISSUE TITLE
PyPy v7.3.10 release | PyPy

### ISSUE THREAD

**Issue by mattip** [pypy/pypy.org#82]

**Comment by reagle** [comment]
I was intrigued you have arm64 support now, but [your link](https://www.pypy.org/download.html) for the Mac build is [broken](https://downloads.python.org/pypy/pypy3.9-v7.3.10-osx64.tar.bz2).

**Comment by mattip** [comment]
@reagle: should be fixed now, thanks.

@renjsum: when it is ready :). We intend working on 3.10 as soon as the dust settles around this release. Hopefully we will not hit too many snags and can release in 4-6 months.

**Comment by HIRANO-Satoshi** [comment]
I donated for the Apple M1 support. Congrats and thanks!

When will the release appear on homebrew?

**Comment by mattip** [comment]
Thanks for the donation. I don't know how the homebrew updates work. I think someone needs to champion a recipe update somewhere?

**Comment by reagle** [comment]
@HIRANO-Satoshi, looking at [the history](https://github.com/Homebrew/homebrew-core/commits/fa4d054561f117eed9076d155d4b6674500ac48d/Formula/pypy3.rb) it looks like there might be a delay of a month or two. Perhaps it'll show in pyenv before then?

**Comment by HIRANO-Satoshi** [comment]
I see. 

@tonydaloney has just started a PR for 3.8 and 3.9 as there is only 3.7 on Homebrew. His TODO has an update to the latest version. I'll wait for it.

https://github.com/Homebrew/homebrew-core/pull/117699

It's is a good chance to say thanks to all you Pypy guys. Here is our work with Pypy. Pypy is stable and reliable. Thank you very much.

   https://rq.land
